strncpy out of bounds fix
embrace-io/embrace-android-sdk pull request #1785
Opened 2024-12-28 21:04 UTC by priettt

We use strncpy in many places. In almost all places, we call it with the size of the destination array. That means something like this:

```
char destinationArray[3]
char sourceArray[5]
emb_strncpy(destinationArray, sourceArray, sizeof(destinationArray))
```

In that case, sizeof(destinationArray) will be 3. That means the while loop will execute until 4, and we will try to write `src[3]` to `dst[3]`, which is out of bounds.

While C might let you write out of bounds, it may cause memory corruption or failure. 

Changes: 
- Modified the while loop so `i` won't be equal to `destination_len`.
- Added a `source[i] != '\0'` verification in case the source is smaller than the destination. Strings passed in src should end in that termination char. If they don't, we might face another OOB. We could solve this by also passing source_len as a parameter.
- Added some test cases.
- Improved naming.

2024-12-31 19:12 UTC, bidetofevil approved these changes
welp

2025-01-02 10:04 UTC, fractalwrench requested changes
Good catch on the off-by-one problem. I think we need to make one change to how the string is copied over, then this is good to go

2025-01-02 10:04 UTC, fractalwrench commented on embrace-android-sdk/src/main/cpp/utils/string_utils.c
> +    while (i < destination_len && source[i] != '\0') {
This change means the null termination character is not copied to the destination array, which could cause various problems downstream as lots of C code assumes that strings must have that character.

2025-01-06 14:14 UTC, fractalwrench approved these changes

2025-01-06 14:59 UTC, merged