user TapBreadcrumbDataSource in the session message
embrace-io/embrace-android-sdk pull request #665
Opened 2024-04-05 18:55 UTC by nelsitoPuglisi

## Goal

## Testing

## Release Notes

**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>

2024-04-05 18:55 UTC, nelsitoPuglisi commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/665?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#665** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/665?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#663** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/663?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#662** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/662?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nelsitoPuglisi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-09 20:41 UTC, bidetofevil requested changes
I think we need to keep the v1 implementation working until this is released and we know that v2 is working completely

2024-04-09 21:32 UTC, bidetofevil commented on embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Breadcrumbs.kt
> -    @Json(name = "tb")
As discussed off line, this should be fine

2024-04-09 21:33 UTC, bidetofevil approved these changes
LGTM! Sorry for the confusion

2024-04-10 09:45 UTC, fractalwrench approved these changes
LGTM

2024-04-10 17:01 UTC, merged